version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: always
